name: Laravel Vue 20240124

services:
  client:
    build: docker/client
    working_dir: /app
    ports:
      - 5173:5173
    volumes:
      - ./client/:/app

  api:
    build: docker/api
    working_dir: /app
    volumes:
      - ./api/:/app
      - ./api/storage/app/public/:/app/public/storage
      - ./docker/api/api.ini:/usr/local/etc/php/conf.d/99-api.ini

  api-web:
    image: nginx:1-alpine
    volumes:
      - ./api/:/usr/share/nginx/html:ro
      - ./api/storage/app/public/:/usr/share/nginx/html/public/storage:ro
      - ./docker/api-web/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
     - 80:80
    depends_on:
      - api

  db:
    image: postgres:17.2
    platform: linux/x86_64
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app
    volumes:
      - app_db_data:/var/lib/postgresql/data

volumes:
  app_db_data:
